import 'package:build/build.dart';

/// A no-op builder that proves the package:build wiring works end-to-end.
///
/// Phase 0 of the AOT-without-conduit-build migration (see
/// docs/AOT_WITHOUT_BUILD.md). It emits one `.conduit.stamp.dart` file
/// per Dart library it sees, containing nothing but a comment. Real
/// builders that replace mirror-based discovery (Channel, Controller,
/// ManagedObject, Serializable, Configuration) will live alongside this
/// file in later phases.
class StampBuilder implements Builder {
  @override
  Map<String, List<String>> get buildExtensions => const {
        '.dart': ['.conduit.stamp.dart'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final input = buildStep.inputId;
    final output = input.changeExtension('.conduit.stamp.dart');
    await buildStep.writeAsString(
      output,
      '// Generated by conduit_build_runner. Source: ${input.path}\n',
    );
  }
}
