name: Conduit
repository: https://github.com/conduit-dart/conduit
packages:
  - packages/**
ignore:
  - packages/cli/templates/**
  - packages/tmp/**
  - packages/not_tests/**
  - packages/runtime_test_packages/**
  - packages/isolate_exec_test_packages/**
command:
  version:
    linkToCommits: true
  bootstrap:
    usePubspecOverrides: true
scripts:
  test-unit:
    run: melos exec -c1 --fail-fast --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart test"
    select-pacakge:
      no-private: true
  test-with-coverage:
    run: melos exec --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart $MELOS_ROOT_PATH/utils/unused_port.dart | dart pub global run coverage:test_with_coverage --port -"
    select-pacakge:
      no-private: true
  analyze: melos exec -- dart analyze .
  upgrade: melos exec -- dart pub upgrade
  activate-all:
    run: melos exec -- "dart pub global activate '\$MELOS_PACKAGE_NAME'"
    select-pacakge:
      no-private: true
  cache-source:
    run: melos exec -- "mkdir -p '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION' && cp -rf '\$MELOS_PACKAGE_PATH'/* '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION'"
    select-pacakge:
      no-private: true
  cache-source-win:
    run: melos exec -- "mkdir %PUB_CACHE%hosted\pub.dev\%MELOS_PACKAGE_NAME%-%MELOS_PACKAGE_VERSION% && xcopy %MELOS_PACKAGE_PATH% %PUB_CACHE%hosted\pub.dev\%MELOS_PACKAGE_NAME%-%MELOS_PACKAGE_VERSION% /Y /s /e"
    select-pacakge:
      no-private: true
  hard-clean:
    run: melos exec -- "rm -rf '\$MELOS_PACKAGE_PATH/.dart_tool' '\$MELOS_PACKAGE_PATH/pubspec.lock'"
  gen-docs:
    run: |
      melos exec --ignore "*common*" --ignore "fs_test_agent" -- "dart doc"
    select-pacakge:
      no-private: true
  fix:
    run: melos exec --fail-fast --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart fix --apply ."
    select-pacakge:
      no-private: true
environment:
  sdk: ">=3.0.1 <4.0.0"
  
