name: Conduit
repository: https://github.com/conduit-dart/conduit
packages:
  - packages/**
ignore:
  - packages/conduit/templates/**
  - packages/tmp/**
  - packages/runtime_test_packages/**
  - packages/isolate_exec_test_packages/**
command:
  version:
    linkToCommits: true
scripts:
  test-unit:
    run: . ci/.env && melos exec --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart test -j1 -x cli test/*" #TODO: file a bug report with dart:mirrors
    select-pacakge:
      no-private: true
  test-with-coverage:
    run: . ci/.env && melos exec --ignore "*common*" --ignore "*application*" --ignore "*dependency*" -- "dart $MELOS_ROOT_PATH/utils/unused_port.dart | dart pub global run coverage:test_with_coverage --port -"
    select-pacakge:
      no-private: true
  analyze: melos exec -- pub global run tuneup check
  activate-all:
    run: melos exec -- "dart pub global activate '\$MELOS_PACKAGE_NAME'"
    select-pacakge:
      no-private: true
  cache-source:
    run: melos exec -- "mkdir -p '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION'; cp -R '\$MELOS_PACKAGE_PATH'/* '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION' && ls '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION/' && yq -i 'del(.dependency_overrides)' '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION/pubspec.yaml'"
    select-pacakge:
      no-private: true
  strip-overrides:
    run: melos exec -- "yq -i 'del(.dependency_overrides)' '\$MELOS_PACKAGE_PATH/pubspec.yaml'"
    select-pacakge:
      no-private: true
  apply-overrides:
    run: melos exec -- "if [ -f '\$MELOS_PACKAGE_PATH/overrides.yaml' ]; then yq -i '. *= load(\"\$MELOS_PACKAGE_PATH/overrides.yaml\")' '\$MELOS_PACKAGE_PATH/pubspec.yaml'; fi"
  hard-clean:
    run: melos exec -- "rm -rf '\$MELOS_PACKAGE_PATH/.dart_tool' '\$MELOS_PACKAGE_PATH/pubspec.lock'"
environment:
  sdk: ">=2.12.0 <3.0.0"
  
