name: wildfire
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.12.0-0 <4.0.0"

dependencies:
  conduit: ^7.0.0
  conduit_core: ^7.0.0

dev_dependencies:
  test: ^1.25.2
  conduit_test: ^7.0.0
  build_runner: ^2.14.1
  conduit_build_runner: ^7.0.0
