name: wildfire
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  conduit: ^4.4.0
  conduit_core: ^4.4.0

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.8
