name: conduit_codable
version: 4.2.2
homepage: https://github.com/conduit-dart/conduit-codable
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types.
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  meta: ^1.3.0
dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
