name: wildfire
description: An conduit application with a database connection and data model.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  conduit: ^5.0.1
  conduit_core: ^5.0.1
  conduit_postgresql: ^5.0.1

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^5.0.1
