name: wildfire
description: An conduit application with a database connection, data model and OAuth 2.0 endpoints.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  conduit: ^4.3.0
  conduit_core: ^4.3.0
  conduit_postgresql: ^4.3.0

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.0
