FROM dart:beta

COPY ci/ ci/
COPY packages/ packages/
COPY pubspec.yaml pubspec.yaml
RUN dart pub global activate -spath packages/cli
RUN dart pub global activate melos
ENV PUB_CACHE=/root/.pub-cache
ENV PATH=$PATH:$PUB_CACHE/bin
RUN melos cache-source --no-select
RUN dart --disable-analytics
