name: application
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dependency:
    path: ../dependency/
  meta: ^1.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
