name: application
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  dependency:
    path: ../dependency/
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
