name: conduit_common
description: Common classes shared by conduit projects.
version: 6.0.0
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  conduit_open_api: ^6.0.0

dev_dependencies:
  lints: ^6.0.0
