name: dependency
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  conduit_runtime:
    path: ../../runtime

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
