name: conduit_runtime
version: 3.2.7
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
repository: https://github.com/conduit-dart/conduit-runtime
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^5.1.0
  args: ^2.0.0
  conduit_isolate_exec: ^3.2.7
  io: ^1.0.3
  package_config: ^2.1.0
  path: ^1.8.0
  pubspec: ^2.0.1
  yaml: ^3.1.0
dev_dependencies:
  fs_test_agent:
    path: ../fs_test_agent
  lint: ^1.5.0
  test: ^1.21.6
dependency_overrides:
  conduit_isolate_exec:
    path: ../isolate_exec
