version: "3.3"
   
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: dart
      POSTGRES_PASSWORD: dart
      POSTGRES_DB: dart_test
    ports:
      - 0.0.0.0:5432:5432
      