name: conduit_core
version: 4.3.8
homepage: https://github.com/conduit-dart/conduit
description: This is the core of the framework.
environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  analyzer: ^5.1.0
  args: ^2.1.1
  collection: ^1.15.0
  conduit_common: ^4.3.7
  conduit_config: ^4.3.7
  conduit_isolate_exec: ^4.3.7
  conduit_open_api: ^4.3.7
  conduit_password_hash: ^4.3.7
  conduit_runtime: ^4.3.7
  crypto: ^3.0.2
  io: ^1.0.3
  logging: ^1.0.0
  meta: ^1.1.5
  path: ^1.8.0
  postgres: ^2.3.1
  pub_semver: ^2.0.0
  recase: ^4.1.0
  yaml: ^3.1.0
dev_dependencies:
  conduit_postgresql:
    path: ../postgresql
  conduit_test:
    path: ../test_harness
  fs_test_agent:
    path: ../fs_test_agent
  http: ^0.13.0
  lints: ^2.0.1
  matcher: ^0.12.12
  mockito: ^5.3.2
  test: ^1.21.6
  web_socket_channel: ^2.2.0
