name: conduit_test
version: 5.0.1
homepage: https://github.com/conduit-dart/conduit
description: Utilities for writing automated tests for Conduit applications
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  test: ^1.21.6
  matcher: ^0.12.12
  conduit_core: ^5.0.1
dev_dependencies:
  conduit_postgresql:
    path: ../postgresql
  lints: ^3.0.0
  test_core: ^0.6.0
