branches:
  only:
    - master
  except:
    - gh-pages
    - docs/source

services:
  - postgresql96

environment:
  matrix:
    - TEST_DIR: conduit_test
    - TEST_DIR: conduit
    - POSTGRES_PORT: 5432

install:
  - ps: wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip -OutFile dart-sdk.zip
  - cmd: echo "Unzipping dart-sdk..."
  - cmd: 7z x dart-sdk.zip -o"C:\tools" -y > nul
  - set PATH=%PATH%;C:\tools\dart-sdk\bin
  - set PATH=%PATH%;%APPDATA%\Pub\Cache\bin
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%

build: off

test_script:
  - cmd: psql -U postgres -c "create user conduit_test_user with createdb;"
  - cmd: psql -U postgres -c "alter user conduit_test_user with password 'conduit!';"
  - cmd: psql -U postgres -c "create database conduit_test_db;"
  - cmd: psql -U postgres -c "grant all on database conduit_test_db to conduit_test_user;"
  - cd %TEST_DIR%
  - pub get
  - pub run test -j1

cache:
  - C:\Users\appveyor\AppData\Roaming\Pub\Cache
