import 'package:build_test/build_test.dart';
import 'package:conduit_build_runner/src/stamp_builder.dart';
import 'package:test/test.dart';

void main() {
  test('emits a stamp file alongside each Dart input', () async {
    await testBuilder(
      StampBuilder(),
      const {'a|lib/foo.dart': 'class Foo {}\n'},
      outputs: {
        'a|lib/foo.conduit.stamp.dart':
            '// Generated by conduit_build_runner. Source: lib/foo.dart\n',
      },
    );
  });
}
