name: conduit
version: 4.4.0
homepage: https://github.com/conduit-dart/conduit
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  analyzer: ^6.3.0
  args: ^2.1.1
  collection: ^1.15.0
  conduit_common: ^4.3.8
  conduit_config: ^4.3.8
  conduit_core: ^4.4.0
  conduit_isolate_exec: ^4.3.8
  conduit_open_api: ^4.3.8
  conduit_password_hash: ^4.3.8
  conduit_postgresql: ^4.4.0
  conduit_runtime: ^4.3.8
  crypto: ^3.0.2
  io: ^1.0.3
  logging: ^1.0.0
  meta: ^1.1.5
  path: ^1.8.0
  postgres: ^3.0.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0
dev_dependencies:
  conduit_test:
    path: ../test_harness
  fs_test_agent:
    path: ../fs_test_agent
  http: ^1.0.0
  lints: ^3.0.0
  matcher: ^0.12.12
  mockito: ^5.3.2
  test: ^1.21.6
  web_socket_channel: ^2.2.0
executables:
  conduit: conduit
