name: conduit_config
version: 3.2.3
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/conduit-dart/conduit-config.git
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  conduit_runtime: ^3.2.3
  meta: ^1.3.0
  yaml: ^3.1.0
dev_dependencies:
  lint: ^1.5.0
  test: ^1.21.6
dependency_overrides:
  conduit_isolate_exec:
    path: ../isolate_exec
  conduit_runtime:
    path: ../runtime
