name: conduit_config
version: 4.2.2
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/conduit-dart/conduit-config.git
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  conduit_runtime: ^4.2.2
  meta: ^1.3.0
  yaml: ^3.1.0
dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
