name: conduit_open_api
version: 4.3.6
homepage: https://github.com/conduit-dart/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  conduit_codable: ^4.3.6
  meta: ^1.1.5
dev_dependencies:
  lints: ^2.0.1
  test: ^1.3.0
