name: conduit_open_api
version: 5.0.1
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
home: https://www.theconduit.dev
repository: https://github.com/conduit-dart/conduit
issue_tracker: https://github.com/conduit-dart/conduit/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  conduit_codable: ^5.0.1
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
