name: Docs

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:
    branches:
    - master

concurrency:
  group: "documentation"
  cancel-in-progress: true
    
jobs:
  docs:
    if: |
      github.event_name == 'workflow_dispatch' 
      || (github.event_name == 'pull_request' && startsWith(github.head_ref, 'docs/') 
          && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    - name: Install melos
      run: dart pub global activate melos
    - name: Generate docs
      run: melos bootstrap && melos gen-docs && echo "mkdocs-monorepo-plugin==1.0.4" > requirements.txt
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_DOMAIN: docs.theconduit.dev
        CONFIG_FILE: mkdocs.yml
        EXTRA_PACKAGES: build-base
        REQUIREMENTS: requirements.txt
