name: Linux

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "linux-test"
  cancel-in-progress: true

jobs:
  linux:
    if: |
      startsWith(github.head_ref, 'feature/')
      || startsWith(github.head_ref, 'fix/')
      || startsWith(github.head_ref, 'refactor/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_args: [melos test-unit-scoped, dart tool/generated_test_runner.dart]
    env:
      TEST_DIR: packages/core
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dependencies
        run: |
          dart pub global activate melos
          dart pub get --directory=packages/isolate_exec_test_packages/test_package
          melos bootstrap
          melos cache-source
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: . ../../ci/.env && ${{ matrix.runner_args }}