name: Linux

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "linux-test"
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    container: centos/python-38-centos7:latest
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: dev
    - name: Setup Conduit
      run: |
        dart pub global activate -spath packages/cli
    - name: Run tests
      working-directory: ../
      run: |
        conduit create -t db_and_auth wildfire
        cd wildfire/
        echo "----------- Building test project -----------"
        conduit build
        conduit db generate
  unit:
    needs: smoke
    if: |
      startsWith(github.head_ref, 'feature/')
      || startsWith(github.head_ref, 'fix/')
      || startsWith(github.head_ref, 'refactor/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_args: [melos test-unit, dart tool/generated_test_runner.dart]
    env:
      TEST_DIR: packages/core
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: dev
      - name: Get Dependencies
        run: |
          dart pub global activate melos
          melos bootstrap
          melos cache-source
          dart pub get --directory=packages/isolate_exec_test_packages/test_package --offline
          dart pub get --directory=packages/runtime_test_packages/application --offline
          dart pub get --directory=packages/runtime_test_packages/dependency --offline
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: . ../../ci/.env && ${{ matrix.runner_args }}