name: Linux

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "linux-test"
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: dev
    - name: Setup Conduit
      run: |
        dart pub global activate -spath packages/cli
        dart pub global activate melos
        melos cache-source
    - name: Run tests
      working-directory: ../
      run: |
        conduit create -t db_and_auth --offline wildfire
        cd wildfire/
        echo "----------- Building test project -----------"
        conduit build
        conduit db generate
  unit:
    needs: smoke
    if: |
      startsWith(github.head_ref, 'feature/')
      || startsWith(github.head_ref, 'fix/')
      || startsWith(github.head_ref, 'refactor/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_args: [melos test-unit, dart tool/generated_test_runner.dart]
    env:
      TEST_DIR: packages/core
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          PGPASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: conduit_test_user
          MYSQL_PASSWORD: conduit!
          MYSQL_DATABASE: conduit_test_db
          MYSQL_PORT: 13306
          MYSQL_INITDB_TEMP_TABLE_USE: true
          MYSQL_INIT_COMMAND: "GRANT SELECT ON information_schema.* TO 'conduit_test_user'@'localhost'; set global sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';"
        ports:
          - 13306:3306
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: dev
      - name: Get Dependencies
        run: |
          dart pub global activate -spath packages/cli
          dart pub global activate melos
          melos bootstrap
          melos cache-source
          dart pub get --directory=packages/isolate_exec_test_packages/test_package --offline
          dart pub get --directory=packages/runtime_test_packages/application --offline
          dart pub get --directory=packages/runtime_test_packages/dependency --offline
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: . ../../ci/.env && ${{ matrix.runner_args }}
