name: Test Suite

on:
  release:

jobs:
  conduit_test:
    env:
      TEST_DIR: conduit_test
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
      POSTGRES_PORT: 15432
      RUNNER_CMD: pub run test -j 1 -r expanded
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable, beta, dev]
        runner_args: [-t cli, -x cli]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: ${{ env.RUNNER_CMD }}

  conduit:
    env:
      TEST_DIR: conduit
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
      POSTGRES_PORT: 15432
      RUNNER_CMD: pub run test -j 1 -r expanded
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable, beta, dev]
        runner_args: [-t cli, -x cli]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: ${{ env.RUNNER_CMD }} ${{ matrix.runner_args }}

  conduit_tool:
    env:
      TEST_DIR: conduit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable, beta, dev]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: dart tool/generated_test_runner.dart
