name: Smoke

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "smoke-test"
  cancel-in-progress: true

jobs:
  linux:
    runs-on: linux-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: dev
    - name: Setup Conduit
      run: |
        dart pub global activate -spath packages/cli
    - name: Run tests
      working-directory: ~/
      run: |
        conduit create -t db_and_auth wildfire
        cd wildfire/
        conduit build