name: Test Suite

on:
  pull_request:
    branches: [master]

jobs:
  test_harness:
    env:
      TEST_DIR: test_harness
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
      POSTGRES_PORT: 15432
      RUNNER_CMD: pub run test -r expanded
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_args: [-t cli, -x cli]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: ${{ env.RUNNER_CMD }}

  conduit:
    env:
      TEST_DIR: conduit
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
      POSTGRES_PORT: 15432
      RUNNER_CMD: pub run test -r expanded
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_args: [-t cli, -x cli]
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: ${{ env.RUNNER_CMD }} ${{ matrix.runner_args }}

  conduit_tool:
    env:
      TEST_DIR: ci
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: conduit_test_user
          POSTGRES_PASSWORD: conduit!
          POSTGRES_DB: conduit_test_db
          POSTGRES_PORT: 15432
        ports:
          - 15432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dependencies
        working-directory: ${{ env.TEST_DIR }}
        run: dart pub get
      - name: Get Conduit Dependencies
        working-directory: conduit
        run: dart pub get
      - name: Run tests
        working-directory: ${{ env.TEST_DIR }}
        run: dart generated_test_runner.dart
      - run: cat _build/packages/conduit/pubspec.yaml && ls _build/packages
        if: always()
